CREATE TABLE `offline_answer_sheets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`offlineContestId` int NOT NULL,
	`version` varchar(32) DEFAULT 'v1',
	`questions` json NOT NULL,
	`answerKey` json NOT NULL,
	`pdfUrl` text,
	`printInstructions` text,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `offline_answer_sheets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `offline_contests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(512) NOT NULL,
	`edition` varchar(128),
	`description` text,
	`targetSchoolCount` int DEFAULT 0,
	`targetParticipantCount` int DEFAULT 0,
	`registrationDeadline` timestamp,
	`contestDate` timestamp,
	`resultsDate` timestamp,
	`shippingDeadline` timestamp,
	`testFormat` enum('paper_scan','paper_manual','hybrid') DEFAULT 'paper_scan',
	`questionsCount` int DEFAULT 0,
	`passingScore` float DEFAULT 90,
	`requireVideoProof` boolean DEFAULT false,
	`requireTeacherSignature` boolean DEFAULT true,
	`requireParentConsent` boolean DEFAULT true,
	`status` enum('draft','registration','active','scoring','results','shipping','completed') NOT NULL DEFAULT 'draft',
	`linkedSnapshotId` int,
	`rulesText` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `offline_contests_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `offline_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`offlineContestId` int NOT NULL,
	`participantId` int,
	`schoolId` int,
	`participantName` varchar(255),
	`participantEmail` varchar(320),
	`ageGroup` varchar(64),
	`grade` varchar(32),
	`rawScore` float,
	`maxScore` float,
	`scorePercent` float,
	`correctAnswers` int DEFAULT 0,
	`totalQuestions` int DEFAULT 0,
	`rank` int,
	`isWinner` boolean DEFAULT false,
	`isLaureate` boolean DEFAULT false,
	`scanStatus` enum('pending','scanned','ocr_done','verified','error') DEFAULT 'pending',
	`scanImageUrl` text,
	`ocrRawText` text,
	`ocrAnswers` json,
	`ocrConfidence` float,
	`manualCorrections` json,
	`teacherSignatureVerified` boolean DEFAULT false,
	`parentConsentReceived` boolean DEFAULT false,
	`videoUrl` text,
	`videoVerificationId` int,
	`verificationStatus` enum('pending','verified','rejected','manual_review') DEFAULT 'pending',
	`awardAssigned` boolean DEFAULT false,
	`awardId` int,
	`shippingBatchId` int,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `offline_submissions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `school_registrations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`offlineContestId` int NOT NULL,
	`schoolId` int NOT NULL,
	`registeredAt` timestamp NOT NULL DEFAULT (now()),
	`expectedParticipants` int DEFAULT 0,
	`actualParticipants` int DEFAULT 0,
	`answerSheetsRequested` int DEFAULT 0,
	`answerSheetsSent` boolean DEFAULT false,
	`answerSheetsSentAt` timestamp,
	`submissionsReceived` int DEFAULT 0,
	`status` enum('registered','sheets_sent','submitted','scored','awarded') NOT NULL DEFAULT 'registered',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `school_registrations_id` PRIMARY KEY(`id`)
);
