CREATE TABLE `anomaly_cases` (
	`id` int AUTO_INCREMENT NOT NULL,
	`participantEmail` varchar(320) NOT NULL,
	`participantName` varchar(255),
	`contestEdition` varchar(128),
	`quizId` int,
	`snapshotId` int,
	`anomalyType` enum('recording_interrupted','server_timeout','ajax_error','connection_lost','quiz_not_saved','session_expired','plugin_crash','black_swan','other') NOT NULL,
	`serverLogEvidence` text,
	`telemetryEvidence` json,
	`simulationReference` text,
	`errorCode` varchar(64),
	`errorMessage` text,
	`occurredAt` timestamp NOT NULL DEFAULT (now()),
	`credibilityScore` float,
	`credibilityReason` text,
	`isSuspiciousBehavior` boolean DEFAULT false,
	`suspicionReason` text,
	`status` enum('detected','under_review','approved','rejected','retry_used') NOT NULL DEFAULT 'detected',
	`adminDecision` text,
	`adminId` int,
	`decidedAt` timestamp,
	`retryToken` varchar(128),
	`retryTokenExpiresAt` timestamp,
	`retryUsedAt` timestamp,
	`notificationSentAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `anomaly_cases_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `anomaly_patterns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`anomalyType` varchar(64) NOT NULL,
	`detectionSignals` json NOT NULL,
	`isBlackSwan` boolean DEFAULT false,
	`discoveredInSimulation` varchar(128),
	`occurrenceCount` int DEFAULT 0,
	`lastSeenAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `anomaly_patterns_id` PRIMARY KEY(`id`)
);
