CREATE TABLE `behavioral_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`profileId` int NOT NULL,
	`eventType` enum('unusual_speed','unusual_slowness','copy_paste_detected','tab_switch','long_pause','answer_changed_many','perfect_score_fast','parent_intervention','complaint_submitted','dispute_raised','late_submission','late_registration','bulk_registration','missing_consent','wrong_category','technical_failure_org') NOT NULL,
	`severity` enum('info','warning','critical') NOT NULL DEFAULT 'info',
	`description` text NOT NULL,
	`evidence` json,
	`contestEdition` varchar(100),
	`resolvedAt` timestamp,
	`resolution` text,
	`occurredAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `behavioral_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `behavioral_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`participantEmail` varchar(320) NOT NULL,
	`participantName` varchar(255),
	`schoolId` int,
	`contestEditions` json,
	`role` enum('child','parent','teacher') NOT NULL,
	`ageGroup` enum('przedszkolak','klasy_1_3','klasy_4_6','klasy_7_8','liceum'),
	`stressIndicators` json,
	`cheatingRiskScore` int,
	`technicalSkillLevel` enum('low','medium','high'),
	`averageCompletionTimeMs` int,
	`averageScore` int,
	`participationCount` int DEFAULT 0,
	`interventionRiskScore` int,
	`complaintRiskScore` int,
	`previousComplaints` int DEFAULT 0,
	`previousInterventions` int DEFAULT 0,
	`organizationalRiskScore` int,
	`previousIncidents` int DEFAULT 0,
	`schoolsManaged` int DEFAULT 1,
	`predictedRisks` json,
	`aiNeedsAnalysis` text,
	`aiRecommendations` text,
	`predictionConfidence` int,
	`isHighRisk` boolean DEFAULT false,
	`requiresSpecialAttention` boolean DEFAULT false,
	`specialAttentionNote` text,
	`telemetrySessions` json,
	`videoVerifications` json,
	`anomalyCases` json,
	`lastUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `behavioral_profiles_id` PRIMARY KEY(`id`)
);
